# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


_welcome:
    pattern:      /
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Home:index }
    
_skills:
    resource:     "@TriebawerkeSkilleratorBundle/Controller/SkillsController.php"
    type:         annotation
    prefix:       /skills

_skills_update:
    pattern:      /skills/{id}/update
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Skills:update }

_skills_show:
    pattern:      /skills/show/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Skills:show }

_skills_edit:
    pattern:      /skills/edit/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Skills:edit }      

_skills_delete:
    pattern:      /skills/delete/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Skills:delete}

_level_new:
    pattern:      /level/new
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Level:new}
    
_level:
    pattern:      /level
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Level:index}

level_update:
    pattern:      /level/update/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Level:update}
        
_level_create:
    pattern:      /level/create
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Level:create} 
    
_level_show:
    pattern:      /level/show/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Level:show}
    
_level_delete:
    pattern:      /level/delete/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Level:delete}
    
_level_edit:
    pattern:      /level/edit/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Level:edit}
        
certificate:
    pattern:      /certificate
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Certificate:index}

certificate_show:
    pattern:      /certificate/show/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Certificate:show}  
  
certificate_edit:
    pattern:      /certificate/edit/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Certificate:edit}
    
certificate_update:
    pattern:      /certificate/update/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Certificate:update}    

certificate_new:
    pattern:      /certificate/new
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Certificate:new}

certificate_create:
    pattern:      /certificate/create
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Certificate:create} 

certificate_delete:
    pattern:      /certificate/delete/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Certificate:delete}

userskills:
    pattern:      /userskills
    defaults:     { _controller: TriebawerkeSkilleratorBundle:UserSkills:index}        
    
userskills_show:
    pattern:      /userskills/show/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:UserSkills:show}
    
userskills_edit:
    pattern:      /userskills/edit/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:UserSkills:edit}

userskills_update:
    pattern:      /userskills/update/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:UserSkills:update}
    
userskills_create:
    pattern:      /userskills/create
    defaults:     { _controller: TriebawerkeSkilleratorBundle:UserSkills:create}

userskills_new:
    pattern:      /userskills/new
    defaults:     { _controller: TriebawerkeSkilleratorBundle:UserSkills:new} 

userskills_delete:
    pattern:      /userskills/delete/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:UserSkills:delete} 

user:
    pattern:      /user
    defaults:     { _controller: TriebawerkeUserBundle:User:index}        
    
user_show:
    pattern:      /user/show
    defaults:     { _controller: TriebawerkeUserBundle:User:show}
    
user_edit:
    pattern:      /user/edit
    defaults:     { _controller: TriebawerkeUserBundle:User:edit}
    
user_create:
    pattern:      /user/create
    defaults:     { _controller: TriebawerkeUserBundle:User:create}

user_new:
    pattern:      /user/new
    defaults:     { _controller: TriebawerkeUserBundle:User:new} 

user_delete:
    pattern:      /user/delete
    defaults:     { _controller: TriebawerkeUserBundle:User:delete}      

user_update:
    pattern:      /user/update
    defaults:     { _controller: TriebawerkeUserBundle:User:update}

     
company:
    pattern:      /company
    defaults:     { _controller: TriebawerkeUserBundle:Company:index}        
    
company_show:
    pattern:      /company/show/{id}
    defaults:     { _controller: TriebawerkeUserBundle:Company:show}
    
company_edit:
    pattern:      /company/edit/{id}
    defaults:     { _controller: TriebawerkeUserBundle:Company:edit}
    
company_create:
    pattern:      /company/create
    defaults:     { _controller: TriebawerkeUserBundle:Company:create}

company_new:
    pattern:      /company/new
    defaults:     { _controller: TriebawerkeUserBundle:Company:new} 

company_delete:
    pattern:      /company/delete
    defaults:     { _controller: TriebawerkeUserBundle:Company:delete}      

company_update:
    pattern:      /company/update/{id}
    defaults:     { _controller: TriebawerkeUserBundle:Company:update}     

team:
    pattern:      /team
    defaults:     { _controller: TriebawerkeUserBundle:Team:index}        
    
team_show:
    pattern:      /team/show/{id}
    defaults:     { _controller: TriebawerkeUserBundle:Team:show}
    
team_edit:
    pattern:      /team/edit/{id}
    defaults:     { _controller: TriebawerkeUserBundle:Team:edit}
    
team_create:
    pattern:      /team/create
    defaults:     { _controller: TriebawerkeUserBundle:Team:create}

team_new:
    pattern:      /team/new
    defaults:     { _controller: TriebawerkeUserBundle:Team:new} 

team_delete:
    pattern:      /team/delete
    defaults:     { _controller: TriebawerkeUserBundle:Team:delete}      

team_update:
    pattern:      /team/update/{id}
    defaults:     { _controller: TriebawerkeUserBundle:Team:update} 

goal:
    pattern:      /goal
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Goal:index}        
    
goal_show:
    pattern:      /goal/show/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Goal:show}
    
goal_edit:
    pattern:      /goal/edit/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Goal:edit}
    
goal_create:
    pattern:      /goal/create
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Goal:create}

goal_new:
    pattern:      /goal/new
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Goal:new} 

goal_delete:
    pattern:      /goal/delete
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Goal:delete}      

goal_update:
    pattern:      /goal/update/{id}
    defaults:     { _controller: TriebawerkeSkilleratorBundle:Goal:update} 


login:
    pattern:   /login
    defaults:  { _controller: TriebawerkeSecurityBundle:Security:login }
login_check:
    pattern:   /login_check
    defaults:  { _controller: TriebawerkeSecurityBundle:Security:login }
    
logout:
    pattern:   /logout     
    
registration_register:
    pattern:   /registration/register
    defaults:  { _controller: TriebawerkeUserBundle:Registration:register }

registration_create:
    pattern:   /registration/create
    defaults:  { _controller: TriebawerkeUserBundle:Registration:create }   
   
_home:
    resource:     "@TriebawerkeSkilleratorBundle/Controller/HomeController.php"
    type:         annotation
    prefix:       /home
#    
#_skillerator_secured:
#    resource: "@TriebawerkeSkilleratorBundle/Controller/SecuredController.php"
#    type:     annotation
#    
    