<?php

namespace Triebawerke\SkilleratorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends EntityRepository
{
}