<?php

namespace Triebawerke\SkilleratorBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Symfony\Component\Security\CoreUser\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSkillsRepository extends EntityRepository
{
  public function loadSkillsByUserId($userId)
  {
      $query = $this  
              ->createQueryBuilder('us')
              ->where('us.user_id = :userId')
              ->setParameter('userId', $userId)
              ->getQuery()
              ;
      try
      {
          $userSkills = $query->getResult();
      } catch(NoResutException $e) {
          throw new UserSkillsNotFoundException(sprintf('Unable to find user skills for user id %d', $userId), null, 0, $e);
      }
      
      return $userSkills;
   }

}