<?php

namespace Triebawerke\SkilleratorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserSkillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSkillsRepository extends EntityRepository
{
}